SELECT ID, 
    CASE 
        WHEN(SIZE_OF_COLONY BETWEEN 0 AND 99) THEN "LOW"
        WHEN(SIZE_OF_COLONY BETWEEN 100 AND 999) THEN "MEDIUM"
        WHEN(SIZE_OF_COLONY > 1000) THEN "HIGH"
    END AS SIZE
FROM ECOLI_DATA